# Generated by Django 2.2.7 on 2019-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrantAPI', '0003_updating_created_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrant',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
