# Generated by Django 2.2.7 on 2019-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrantAPI', '0004_hydrant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='test title', max_length=100),
            preserve_default=False,
        ),
    ]
